create table if not exists public.reels (
  firestore_document_id text primary key,
  reel_number text,
  paper_type text,
  reel_size numeric,
  bf text,
  gsm numeric,
  weight numeric,
  consumed_weight numeric,
  current_balance numeric,
  rate numeric,
  supplier text,
  supplier_name text,
  manufacturer_name text,
  status text,
  inward_date timestamptz,
  reserved_for_jc text,
  active_reserved_weight numeric,
  is_archived boolean,
  created_by text,
  updated_by text,
  created_at timestamptz,
  updated_at timestamptz,
  raw_data jsonb not null,
  imported_at timestamptz not null default now(),
  synced_at timestamptz not null default now()
);
