create table if not exists public.finish_good_transactions (
  firestore_document_id text primary key,
  finish_good_id text,
  type text,
  category text,
  quantity numeric,
  remaining_balance numeric,
  rate numeric,
  transaction_date text,
  reference_id text,
  reference_no text,
  invoice_no text,
  place text,
  transporter_name text,
  vehicle_no text,
  vehicle_size text,
  freight numeric,
  holding numeric,
  point text,
  others text,
  receiving_status text,
  receiving_confirmed_at timestamptz,
  receiving_confirmed_by text,
  performed_by text,
  created_by text,
  updated_by text,
  created_at timestamptz,
  updated_at timestamptz,
  is_archived boolean,
  raw_data jsonb not null,
  imported_at timestamptz not null default now(),
  synced_at timestamptz not null default now()
);
