import { supabase } from './config';
import type { UserSession } from '../firebase/authSessionServices';

// Supabase-backed replacement for the Firestore `user_sessions` collection
// CRUD operations only. Table: public.user_sessions (RLS enabled, SELECT +
// INSERT + UPDATE + DELETE - all four are genuinely used by this table).
//
// NOTE: Realtime forced-logout now uses Supabase `postgres_changes` on
// public.user_sessions, so create/delete no longer needs any temporary
// Firebase session mirroring.
//
// Field mapping (Postgres column -> frontend shape):
//   firestore_document_id -> id  (the app-generated session UUID - preserved exactly)
//   user_id                -> userId
//   device_info            -> deviceInfo
//   login_time             -> loginTime
//   last_active            -> lastActive

const SELECT_COLUMNS = 'firestore_document_id, user_id, device_info, login_time, last_active';

const mapRow = (row: any): UserSession => ({
  id: row.firestore_document_id,
  userId: row.user_id,
  deviceInfo: row.device_info,
  loginTime: row.login_time,
  lastActive: row.last_active,
});

/**
 * Creates a new session. The session ID is generated by the caller (Login.tsx,
 * via crypto.randomUUID()) and used as-is for `firestore_document_id` - no new
 * ID strategy introduced here. `raw_data` (NOT NULL) is populated with the
 * same record being written. Mirrors the previous Firestore `setDoc` behavior:
 * errors are not swallowed here, the caller (Login.tsx) handles them.
 */
export const createSession = async (userId: string, sessionId: string, deviceInfo: string): Promise<void> => {
  const now = new Date().toISOString();
  const row = {
    firestore_document_id: sessionId,
    user_id: userId,
    device_info: deviceInfo,
    login_time: now,
    last_active: now,
  };

  const { error } = await supabase.from('user_sessions').insert({ ...row, raw_data: row });

  if (error) {
    console.error('Error creating session:', error);
    throw error;
  }
};

/**
 * Realtime equivalent of the old Firestore `onSnapshot(sessionRef)` listener.
 * It watches for DELETE events on exactly one session row and invokes the
 * callback once when that row disappears (e.g. "log out other devices").
 */
export const listenToSession = (sessionId: string, onDeleted: () => void): (() => void) => {
  let didNotifyDeletion = false;

  const channel = supabase
    .channel(`user_sessions_delete:${sessionId}`)
    .on(
      'postgres_changes',
      {
        event: 'DELETE',
        schema: 'public',
        table: 'user_sessions',
        filter: `firestore_document_id=eq.${sessionId}`,
      },
      () => {
        if (didNotifyDeletion) return;
        didNotifyDeletion = true;
        onDeleted();
      }
    )
    .subscribe((status) => {
      if (status === 'CHANNEL_ERROR') {
        console.error(`Error subscribing to user_sessions realtime channel for ${sessionId}`);
      }
    });

  return () => {
    didNotifyDeletion = true;
    void supabase.removeChannel(channel);
  };
};

/**
 * Deletes a session. Mirrors the previous Firestore behavior exactly:
 * errors are caught and logged but never thrown (a session that's already
 * gone, or a transient failure, must never block the caller).
 */
export const deleteSession = async (sessionId: string): Promise<void> => {
  try {
    const { error } = await supabase.from('user_sessions').delete().eq('firestore_document_id', sessionId);
    if (error) throw error;
  } catch (error) {
    console.error('Error deleting session:', error);
  }
};

/**
 * Refreshes a session's last-active timestamp (keep-alive, called every
 * ~60s from AuthContext's idle timer). Mirrors the previous Firestore
 * `setDoc(merge:true)` behavior: only `lastActive` is meaningfully updated,
 * and ALL errors are silently ignored (the session may already be deleted).
 * `raw_data` is refreshed too (merged, not replaced) so it doesn't go stale.
 */
export const updateSessionActivity = async (sessionId: string): Promise<void> => {
  try {
    const now = new Date().toISOString();
    const { data } = await supabase
      .from('user_sessions')
      .select('raw_data')
      .eq('firestore_document_id', sessionId)
      .maybeSingle();

    const mergedRawData = { ...(data?.raw_data ?? {}), lastActive: now };

    await supabase
      .from('user_sessions')
      .update({ last_active: now, raw_data: mergedRawData })
      .eq('firestore_document_id', sessionId);
  } catch {
    // Ignore errors for activity updates (might be deleted already)
  }
};

/**
 * Fetches all active sessions for a user. Same query shape as before
 * (`where userId == userId`), just via a native column filter.
 */
export const getActiveSessions = async (userId: string): Promise<UserSession[]> => {
  const { data, error } = await supabase
    .from('user_sessions')
    .select(SELECT_COLUMNS)
    .eq('user_id', userId);

  if (error) {
    console.error('Error fetching active sessions:', error);
    throw error;
  }

  return (data || []).map(mapRow);
};

/**
 * Deletes every session for a user except the current one. Mirrors the
 * previous behavior exactly: fetch all sessions, filter out the current
 * one, delete the rest via `deleteSession` (which never throws).
 */
export const deleteAllOtherSessions = async (userId: string, currentSessionId: string): Promise<void> => {
  const sessions = await getActiveSessions(userId);
  const otherSessions = sessions.filter(s => s.id !== currentSessionId);

  await Promise.all(otherSessions.map(session => deleteSession(session.id)));
};
